name: Build image on schedule

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

env:
  SOURCE_REPO: chatwoot/chatwoot
  # GHCR_IMAGE_NAME: ghcr.io/your-org/your-image  # Replace with actual image

jobs:
  build-v4-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    strategy:
      matrix:
        dockerfile: ['Dockerfile.Community', 'Dockerfile.Enterprise']

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4

    - name: Install tools
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Get latest tag from source repo
      id: get_tag
      run: |
        TAG=$(curl -s https://api.github.com/repos/${{ env.SOURCE_REPO }}/tags | jq -r '.[0].name')
        echo "Latest tag: $TAG"
        echo "tag=$TAG" >> "$GITHUB_OUTPUT"

    - name: Check if tag is valid (starts with v4, old enough, and image missing)
      id: check_tag
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ steps.get_tag.outputs.tag }}
      run: |
        set -e

        if [[ "$TAG" != v4* ]]; then
          echo "Tag $TAG does not start with v4. Skipping."
          exit 0
        fi


        echo "Image for $TAG does not exist. Checking age..."

        # Get commit date for tag
        REF_DATA=$(curl -s https://api.github.com/repos/${{ env.SOURCE_REPO }}/git/refs/tags/$TAG)
        SHA=$(echo "$REF_DATA" | jq -r '.object.sha')

        COMMIT_DATA=$(curl -s https://api.github.com/repos/${{ env.SOURCE_REPO }}/commits/$SHA)
        COMMIT_DATE=$(echo "$COMMIT_DATA" | jq -r '.commit.committer.date')

        COMMIT_TS=$(date -d "$COMMIT_DATE" +%s)
        NOW_TS=$(date +%s)
        AGE_DAYS=$(( (NOW_TS - COMMIT_TS) / 86400 ))

        echo "Tag is $AGE_DAYS days old"

        if [ "$AGE_DAYS" -gt 5 ]; then
          echo "should_build=true" >> "$GITHUB_OUTPUT"
        else
          echo "Tag $TAG is too recent (< 6 days)"
        fi

    # - name: Build and push Docker image
    #   if: steps.check_tag.outputs.should_build == 'true'
    #   env:
    #     TAG: ${{ steps.get_tag.outputs.tag }}
    #     IMAGE: ${{ env.GHCR_IMAGE_NAME }}
    #   run: |
    #     echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    #     docker build -t $IMAGE:$TAG --build-arg VERSION=$TAG .
    #     docker push $IMAGE:$TAG

    # - name: Login to GHCR
    #   if: github.event_name != 'pull_request'
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.repository_owner }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    # - name: Build and push
    #   uses: docker/build-push-action@v6
    #   with:
    #     push: ${{ github.event_name != 'pull_request' }}
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}

    # - name: Build and Publish
    #   uses: docker/build-push-action@v5
    #   with:
    #     file: ${{ matrix.dockerfile }}
    #     platforms: linux/amd64
    #     push: true
    #     tags: ghcr.io/${{ github.repository }}:${{ steps.extract_version.outputs.version }}
